methods_to_run:
#  - preprocessing
  - generate_cellpose_input
  - cellpose_inference
  - convert_multiple_cellpose_output_to_zarr
  - export_results



preprocessing:
#  data_zarr_group: "/scratch/bailoni/projects/nastia/2022-03-07/infer_cellpose/data_partial.zarr"
#  data_zarr_group: "/scratch/bailoni/projects/nastia/2022-03-07/infer_cellpose/data.zarr"
  data_zarr_group: "/scratch/bailoni/projects/nastia/macrophages/infer_cellpose/naive_cells_data.zarr"
  datasets_to_process:
    - main_dataset
  channels_to_process:
    - BF
    - DAPI
#    - EXTRA
  main_dataset:
#    input_dir_path: "/scratch/bailoni/projects/nastia/2022-03-07/original_data"
    input_dir_path: "/scratch/bailoni/datasets/nastia/macrophages/mouse16_slideM_preMALDI"
#    input_dir_path: "/g/scb/alexandr/shared/alberto/datasets/nastia/2022-03-07" # Partial dataset naive cells
    projectdir_depth: -4
#    folder_filter: "D3/analysis/transformation/cropped_pre_maldi_channels" #J2
#    crop_size: [500, 500]
#    precrop: "2000:3000, 2000:3000"
#    max_nb_images: 2
    BF: "_ch_0"
#    DAPI: "_ch_1"
    verbose: True
    preprocessing:
#      {}
      BF:
        - {
          function_name: "segmUtils.LIVECellutils.preprocessing.preprocess",
          function_kwargs: { }
#          function_name: "segmUtils.preprocessing.process_images.convert_to_cellpose_style",
#          function_kwargs: { method: "subtract" }
        }
#        - {
#          function_name: "segmUtils.preprocessing.process_images.clip_image_values",
#          function_kwargs: { vmax: 139,
#                             vmin: 84,
#                             invert: True}
#        }
#      DAPI:
#        - {
#          function_name: "segmUtils.preprocessing.process_images.clip_image_values",
#          function_kwargs: { vmax: 80,
#                             vmin: 0,
#                             invert: False }
#        }


generate_cellpose_input:
  generate_for:
    - "cellpose_inference"
  convert_to_cellpose_kwargs:
    cellpose_ch0: "BF"
    cellpose_ch1: "DAPI"


cellpose_inference:
  input_dir: "$EXP_DIR/cellpose_inputs"
  multiple_cellpose_inference_kwargs:
    estimate_diameter: [False]
    overwrite_estimate_diameter:
#      {}
      cyto2: True
    diameter: 17
    chan: 2 # Green
    chan2: 1 # Red
    mask_filter: "_masks"
    cellpose_infer_args:
      - no_npy

    tested_models:
#      cyto2: "cyto2"
#      trained: "/scratch/bailoni/projects/nastia/2022-03-07/train_cellpose/nastia_images/CellposeTraining/3rd/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_03_31_11_31_50.228148"
#      trained: "/scratch/bailoni/projects/nastia/2022-03-07/train_cellpose/nastia_images/CellposeTraining/5/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_04_01_16_05_47.464537_epoch_499"
#      trained: "/scratch/bailoni/projects/nastia/2022-03-07/train_cellpose/nastia_images/CellposeTraining/7/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_04_04_14_51_49.916808_epoch_499"
#      naive_cells_500: "/scratch/bailoni/projects/nastia/2022-03-07/train_cellpose/nastia_images/CellposeTraining/8/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_04_06_06_38_22.894181_epoch_501"
#      naive_cells_2000: "/scratch/bailoni/projects/nastia/2022-03-07/train_cellpose/nastia_images/CellposeTraining/8/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_04_06_06_38_22.894181_epoch_1999"
      naive_cells_3500: "/scratch/bailoni/projects/nastia/2022-03-07/train_cellpose/nastia_images/CellposeTraining/8/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_04_06_06_56_01.576317"


export_results:
  export_images_from_zarr_kwargs:
#    TODO: specify main channel name in cvs and get filters from preprocessing section
    filter_main_image_in_csv:
      main_dataset: "_ch_0"
    export_in_external_segm_folder: True
    datasets_to_export:
#      - {inner_path: "cyto2_diamEst"}
      - {inner_path: "naive_cells_3500_noDiamEst"}
#      - {inner_path: "naive_cells_noDiamEst"}

#compute_scores:
#  configs_to_evaluate:
#    - cyto2
#    - cyto2_alex_CP
#    - cyto2_alex
#    - scratch_alex_CP
#  global_config:
#    dataset_name: alex_labels
#    GT_dir: "/scratch/bailoni/datasets/alex/210920_prostate-v1_cellpose-training-original"
#    GT_filter: "_c0_masks"
#    GT_extension: ".png"
#    only_look_at_top_level: False
#    AP_thresholds: [0.5, 0.75]
#  cyto2:
#    pred_filter: "_cyto2"
#  cyto2_alex_CP:
#    pred_filter: "_cyto2_alex_CP"
#  cyto2_alex:
#    pred_filter: "_cyto2_alex"
#  scratch_alex_CP:
#    pred_filter: "_scratch_alex_CP"
