preprocessing:
  data_zarr_group: "/scratch/bailoni/projects/cellpose_inference_projects/jeany/2023-04-HTpaper/v1_small.zarr"
  main_dataset:
#    crop_size: [500, 500]
    precrop: "1000:2000, 1000:2000"
    max_nb_images: 30
