preprocessing:
  data_zarr_group: "/scratch/bailoni/projects/cellpose_inference_projects/jeany/2023-04-HTpaper/batch1.zarr"
  main_dataset:
    filename_filter_include:
     - "analysis/transformation/cropped_pre_maldi_channels"
     - "Batch1_"
    filename_filter_exclude: "KeyDeleter"
#    crop_size: [500, 500]
#    precrop: "1000:2000, 1000:2000"
#    max_nb_images: 30
    BF: "_ch_1"
    DAPI: "_ch_0"
