methods_to_run:
#  - preprocessing
#  - generate_cellpose_input
  - cellpose_inference
  - convert_multiple_cellpose_output_to_zarr
#  - export_results
#  - compute_scores



preprocessing:
  data_zarr_group: "/scratch/bailoni/datasets/gastrosome_full/data_preprocessed.zarr"
#  data_zarr_group: "$EXP_DIR/data.zarr"
  datasets_to_process:
    - all_datasets
  channels_to_process:
    - BF
    - DAPI
#    - GFP
  all_datasets:
    input_dir_path: "/scratch/bailoni/projects/gastrosome_processing_full/spacem"
    projectdir_depth: -4
    folder_filter: "analysis/transformation/cropped_pre_maldi_channels"
#    crop_size: [500, 500]
    precrop: ":1500, :1500"
#    max_nb_images: 2
    BF: "_ch_1"
    DAPI: "_ch_0"
#    GFP: "_c2"
    verbose: True
    preprocessing:
      BF:
        - {
          function_name: "segmUtils.LIVECellutils.preprocessing.preprocess",
          function_kwargs: { }
#            function_name: "segmUtils.preprocessing.process_images.convert_to_cellpose_style",
#          function_kwargs: { method: "subtract" }
        }
        - {
          function_name: "segmUtils.preprocessing.process_images.clip_image_values",
          function_kwargs: { vmax: 135,
                             vmin: 99,
                             invert: True}
        }
#
      DAPI:
        - {
          function_name: "segmUtils.preprocessing.process_images.clip_image_values",
          function_kwargs: { vmax: 51,
              vmin: 0,
              invert: False}
        }


generate_cellpose_input:
  generate_for:
    - "cellpose_inference"
  convert_to_cellpose_kwargs:
    cellpose_ch0: "BF"
    cellpose_ch1: "DAPI"



cellpose_inference:
  input_dir: "$EXP_DIR/cellpose_inputs"
  multiple_cellpose_inference_kwargs:
    estimate_diameter: [False]
    diameter: 35
    overwrite_estimate_diameter:
      cyto2: False
    chan: 2 # Green
    chan2: 1 # Red
    mask_filter: "_masks"
    cellpose_infer_args:
      - no_npy

    tested_models:
      cyto2: "cyto2"
#      model1: "/scratch/bailoni/projects/gastrosome_processing_full/train-cellpose/CellposeTraining/model_2/training_images/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_05_25_14_41_31.541613"
#      model1b: "/scratch/bailoni/projects/gastrosome_processing_full/train-cellpose/CellposeTraining/model_2/training_images/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_06_02_17_54_04.776568"
      model1c: "/tmp/temp_training_data/training_data_model_2_222/model_2/training_images/models/cellpose_residual_on_style_on_concatenation_off_training_images_2022_06_02_18_38_18.210487"
#      alyona_model: "/scratch/bailoni/projects/alyona/20220322_AB_DKFZHypoxia/cellpose_residual_on_style_on_concatenation_off_train_2021_03_15_18_30_20.533388"



export_results:
  export_images_from_zarr_kwargs:
#    TODO: specify main channel name in cvs and get filters from preprocessing section
    filter_main_image_in_csv:
      all_datasets: "_ch_1"
    export_in_external_segm_folder: True
    datasets_to_export:
#      - {inner_path: "cyto2_diamEst", out_filter: "_cellSegm"}
      - {inner_path: "model1_noDiamEst"}
