methods_to_run:
  - preprocessing
  - generate_cellpose_input
  - cellpose_inference
  - convert_multiple_cellpose_output_to_zarr
  - export_results
#  - compute_scores



preprocessing:
  data_zarr_group: "/scratch/bailoni/datasets/gastrosome_full/data_DrugW8.zarr"
  all_datasets:
    folder_filter: "slide6/W8/analysis/transformation/cropped_pre_maldi_channels"
